(()=>{
  if(typeof renderCharacterDirector!=='function'||typeof state==='undefined')return;
  const kindOf=item=>['element','prop'].includes(item?.kind)?item.kind:'character';
  const characters=()=>state.characters.filter(item=>kindOf(item)==='character');
  const sceneAssets=()=>state.characters.filter(item=>kindOf(item)!=='character');
  const selected=item=>state.sceneCharacterIds.some(id=>String(id)===String(item.id));
  function toggleAsset(item){
    if(selected(item)){state.sceneCharacterIds=state.sceneCharacterIds.filter(id=>String(id)!==String(item.id));for(const token of $$(`.inline-character-mention[data-character-id="${CSS.escape(item.id)}"]`))token.remove();syncPromptValue()}
    else{state.sceneCharacterIds.push(item.id);ensureInlineCharacterMention(item)}
    updateCharacterSummary();renderCharacterDirector();
  }
  function assetCard(item,sceneMode=false){
    const card=document.createElement('article');card.className=`character-card scene-asset-card${selected(item)?' selected':''}`;
    const preview=document.createElement('div');preview.className='character-card-preview';const image=characterPreview(item);if(image){const img=document.createElement('img');img.src=image;img.alt=item.name;img.loading='lazy';preview.append(img)}else preview.textContent=item.name.slice(0,2).toUpperCase();
    const copy=document.createElement('div');const title=document.createElement('b');title.textContent=item.name;const badge=document.createElement('small');badge.className='scene-asset-kind';badge.textContent=kindOf(item)==='prop'?'PROP / OBJECT':'SCENE ELEMENT';const description=document.createElement('p');description.textContent=item.description||item.features||'No scene description yet.';const detail=document.createElement('small');detail.textContent=`${item.references.length} reference${item.references.length===1?'':'s'}${selected(item)?' · In prompt':''}`;copy.append(title,badge,description,detail);
    const actions=document.createElement('div');actions.className='character-card-actions';const use=document.createElement('button');use.type='button';use.className='primary';use.textContent=selected(item)?'Remove from prompt':'Mention in prompt';use.onclick=()=>toggleAsset(item);actions.append(use);if(!sceneMode){const edit=document.createElement('button');edit.type='button';edit.textContent='Edit';edit.onclick=()=>renderSceneAssetEditor(item);actions.append(edit)}card.append(preview,copy,actions);return card;
  }
  renderCharacterLibrary=function(){const body=$('#character-dialog-body');body.innerHTML='';const rows=characters();if(!rows.length){body.innerHTML='<div class="character-empty"><b>No characters yet</b><span>Create the first reusable character identity for this project.</span></div>';return}const grid=document.createElement('div');grid.className='character-grid';for(const item of rows)grid.append(characterCard(item));body.append(grid)};
  function renderElementsLibrary(){const body=$('#character-dialog-body');body.innerHTML='';const rows=sceneAssets();if(!rows.length){body.innerHTML='<div class="character-empty"><b>No elements or props yet</b><span>Create reusable objects, vehicles, locations, set pieces or important scene elements.</span></div>';return}const grid=document.createElement('div');grid.className='character-grid';for(const item of rows)grid.append(assetCard(item));body.append(grid)}
  renderSceneCharacters=function(){const body=$('#character-dialog-body');body.innerHTML='';const rows=state.characters.filter(selected);if(!rows.length){body.innerHTML='<div class="character-empty"><b>Nothing selected for this scene</b><span>Select characters, elements or props, or mention them from the @ gallery.</span></div>';return}const grid=document.createElement('div');grid.className='character-grid';for(const item of rows)grid.append(kindOf(item)==='character'?characterCard(item,true):assetCard(item,true));body.append(grid)};
  window.renderSceneAssetEditor=async function(item=null){
    characterUi.editing=item?.id||null;const body=$('#character-dialog-body');body.innerHTML='<form class="character-editor scene-asset-editor"><label>Type<select name="kind"><option value="prop">Prop / object</option><option value="element">Scene element / location</option></select></label><label>Name<input name="name" maxlength="60" required placeholder="Example: brass compass"></label><label>Scene purpose<textarea name="description" maxlength="1000" placeholder="Where and how this object or element should appear"></textarea></label><label>Visual and physical details<textarea name="features" maxlength="1000" placeholder="Shape, material, color, scale, wear, markings and important details"></textarea></label><label class="scene-asset-reference">Primary reference image<input name="reference" type="file" accept="image/*"><small>Optional · more references can be assigned later</small></label><div class="character-editor-actions"><button type="button" data-cancel>Cancel</button><button class="primary" type="submit">Save element / prop</button></div></form>';
    const form=body.querySelector('form');form.elements.kind.value=kindOf(item)==='character'?'prop':kindOf(item);form.elements.name.value=item?.name||'';form.elements.description.value=item?.description||'';form.elements.features.value=item?.features||'';form.querySelector('[data-cancel]').onclick=()=>{characterUi.tab='elements';renderCharacterDirector()};
    if(item){const remove=document.createElement('button');remove.type='button';remove.className='danger';remove.textContent='Delete';remove.onclick=async()=>{if(!confirm(`Delete ${item.name} and its references?`))return;await api(`/api/characters/${item.id}`,{method:'DELETE'});state.sceneCharacterIds=state.sceneCharacterIds.filter(id=>String(id)!==String(item.id));for(const token of $$(`.inline-character-mention[data-character-id="${CSS.escape(item.id)}"]`))token.remove();syncPromptValue();await loadCharacters();characterUi.tab='elements';renderCharacterDirector()};form.querySelector('.character-editor-actions').prepend(remove)}
    form.onsubmit=async event=>{event.preventDefault();const save=form.querySelector('[type="submit"]');save.disabled=true;save.textContent='Saving…';const payload={project_id:state.project.id,kind:form.elements.kind.value,name:form.elements.name.value.trim(),description:form.elements.description.value.trim(),features:form.elements.features.value.trim(),locks:{face:false,hairstyle:false,age:false,body:true,costume:true,accessories:true}};try{const result=await api(item?`/api/characters/${item.id}`:'/api/characters',{method:item?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const saved=result.character;const file=form.elements.reference.files?.[0];if(file){const assetId=await uploadFile(file);await api('/api/character-references',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({project_id:state.project.id,character_id:saved.id,asset_id:assetId,role:'prop',notes:'Primary visual reference for this '+payload.kind,identity_lock:true})})}await loadCharacters();characterUi.tab='elements';renderCharacterDirector()}catch(error){alert(error.message);save.disabled=false;save.textContent='Save element / prop'}};form.elements.name.focus();
  };
  renderCharacterDirector=function(){
    characterUi.editing=null;$$('[data-character-tab]').forEach(button=>button.classList.toggle('active',button.dataset.characterTab===characterUi.tab));const create=$('#new-character');create.hidden=!['library','elements'].includes(characterUi.tab);create.textContent=characterUi.tab==='elements'?'＋ Create element / prop':'＋ Create character';const chars=characters().length,assets=sceneAssets().length,chosen=state.characters.filter(selected).length;$('#character-dialog-status').textContent=`${chars} character${chars===1?'':'s'} · ${assets} element/prop${assets===1?'':'s'} · ${chosen} in this scene`;if(characterUi.tab==='elements')renderElementsLibrary();else if(characterUi.tab==='scene')renderSceneCharacters();else if(characterUi.tab==='references')renderCharacterReferences();else renderCharacterLibrary();
  };
  $('#new-character').onclick=()=>characterUi.tab==='elements'?renderSceneAssetEditor():renderCharacterEditor();
})();
