(()=>{
  const $=selector=>document.querySelector(selector);
  const collapse=$('#video-edit-collapse'),draw=$('#video-edit-draw'),dialog=$('#video-mask-dialog');
  if(!collapse||!draw||!dialog)return;
  let targetMask=null,placeMask=null,painting=false,tool='target',last=null,sourceObjectUrl='',hasTarget=false,hasPlace=false;
  collapse.onclick=()=>{const panel=$('#video-edit-panel');panel.classList.toggle('collapsed');collapse.textContent=panel.classList.contains('collapsed')?'Expand':'Collapse'};
  const sourceUrl=()=>{const item=typeof state!=='undefined'?state.sourceMedia:null;if(item instanceof File){if(sourceObjectUrl)URL.revokeObjectURL(sourceObjectUrl);sourceObjectUrl=URL.createObjectURL(item);return sourceObjectUrl}return item?.url||$('#source-media').closest('.upload-card')?.querySelector('video')?.src||''};
  const fillBlack=canvas=>{const ctx=canvas.getContext('2d');ctx.fillStyle='#000';ctx.fillRect(0,0,canvas.width,canvas.height)};
  const clearAll=()=>{if(!targetMask)return;fillBlack(targetMask);fillBlack(placeMask);const canvas=$('#video-mask-canvas');canvas.getContext('2d').clearRect(0,0,canvas.width,canvas.height);hasTarget=false;hasPlace=false;$('#video-mask-status').textContent='Paint the target in red'};
  const size=()=>{const video=$('#video-mask-source'),canvas=$('#video-mask-canvas');if(!video.videoWidth)return;canvas.width=video.videoWidth;canvas.height=video.videoHeight;targetMask=document.createElement('canvas');placeMask=document.createElement('canvas');for(const mask of [targetMask,placeMask]){mask.width=canvas.width;mask.height=canvas.height}clearAll()};
  draw.onclick=()=>{const url=sourceUrl();if(!url)return alert('Choose a source video first.');$('#video-mask-operation').value=$('#video-edit-operation').value;$('#video-mask-prompt').value=$('#prompt').value||$('#prompt-editor').innerText;const video=$('#video-mask-source');const prepare=()=>{size();if(video.currentTime>video.duration||!Number.isFinite(video.currentTime))video.currentTime=0;$('#video-mask-status').textContent='Canvas ready — choose Target or Destination'};video.onloadedmetadata=prepare;video.onloadeddata=()=>{if(!targetMask)prepare()};video.src=url;video.load();if(video.readyState>=1)prepare();$('.video-mask-stage').classList.remove('painting');$('#video-mask-status').textContent='Loading drawing canvas…';dialog.showModal()};
  $('#video-mask-close').onclick=()=>dialog.close();
  const stage=$('.video-mask-stage'),canvas=$('#video-mask-canvas'),video=$('#video-mask-source');
  const selectTool=value=>{tool=value;stage.classList.add('painting');video.pause();$('#video-mask-brush').classList.toggle('active',tool==='target');$('#video-mask-place').classList.toggle('active',tool==='place');$('#video-mask-erase').classList.toggle('active',tool==='erase');$('#video-mask-status').textContent=tool==='target'?'Paint the object in red':tool==='place'?'Paint the destination in blue':'Erase marked areas'};
  $('#video-mask-brush').onclick=()=>selectTool('target');$('#video-mask-place').onclick=()=>selectTool('place');$('#video-mask-erase').onclick=()=>selectTool('erase');$('#video-mask-clear').onclick=clearAll;
  const point=event=>{const rect=canvas.getBoundingClientRect();return{x:(event.clientX-rect.left)*canvas.width/rect.width,y:(event.clientY-rect.top)*canvas.height/rect.height}};
  const stroke=(context,from,to,color,erase=false)=>{context.save();context.globalCompositeOperation=erase?'destination-out':'source-over';context.strokeStyle=color;context.lineWidth=Number($('#video-mask-size').value);context.lineCap='round';context.lineJoin='round';context.beginPath();context.moveTo(from.x,from.y);context.lineTo(to.x,to.y);context.stroke();context.restore()};
  const line=(from,to)=>{const visible=canvas.getContext('2d');if(tool==='erase'){stroke(visible,from,to,'#000',true);stroke(targetMask.getContext('2d'),from,to,'#000');stroke(placeMask.getContext('2d'),from,to,'#000');return}const target=tool==='target',mask=(target?targetMask:placeMask).getContext('2d');stroke(visible,from,to,target?'rgba(255,45,45,.68)':'rgba(35,145,255,.68)');stroke(mask,from,to,'#fff');if(target)hasTarget=true;else hasPlace=true};
  canvas.onpointerdown=event=>{if(!targetMask){$('#video-mask-status').textContent='Canvas is still loading — try again in a moment';return}if(!stage.classList.contains('painting'))selectTool('target');painting=true;last=point(event);canvas.setPointerCapture(event.pointerId);line(last,last)};canvas.onpointermove=event=>{if(!painting)return;const next=point(event);line(last,next);last=next};canvas.onpointerup=canvas.onpointercancel=()=>{painting=false;last=null};
  const fileFromCanvas=(source,name)=>new Promise(resolve=>source.toBlob(blob=>resolve(new File([blob],name,{type:'image/png'})),'image/png'));
  $('#video-mask-apply').onclick=async()=>{if(!targetMask||!hasTarget)return alert('Paint the target object in red first.');const operation=$('#video-mask-operation').value,prompt=$('#video-mask-prompt').value.trim();if(operation!=='remove'&&!prompt)return alert('Write what should happen to the selected object.');state.editMask=await fileFromCanvas(targetMask,'painted-target-mask.png');state.editPlacementMask=hasPlace?await fileFromCanvas(placeMask,'painted-destination-mask.png'):null;$('#video-edit-operation').value=operation;const editor=$('#prompt-editor');editor.innerText=prompt;editor.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:prompt}));$('#prompt').value=prompt;const target=$('#video-edit-target');target.value=target.value.trim()||'the manually painted target';draw.textContent=hasPlace?'✓ Target + destination ready':'✓ Target ready';$('#video-mask-status').textContent='Edit setup ready';dialog.close()};
})();

